// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/emailsender/core.go
//
// Generated by this command:
//
//	mockgen -source=pkg/emailsender/core.go -destination=pkg/emailsender/core_mock.go -package=emailsender
//

// Package emailsender is a generated GoMock package.
package emailsender

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEmailSender is a mock of EmailSender interface.
type MockEmailSender struct {
	ctrl     *gomock.Controller
	recorder *MockEmailSenderMockRecorder
	isgomock struct{}
}

// MockEmailSenderMockRecorder is the mock recorder for MockEmailSender.
type MockEmailSenderMockRecorder struct {
	mock *MockEmailSender
}

// NewMockEmailSender creates a new mock instance.
func NewMockEmailSender(ctrl *gomock.Controller) *MockEmailSender {
	mock := &MockEmailSender{ctrl: ctrl}
	mock.recorder = &MockEmailSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailSender) EXPECT() *MockEmailSenderMockRecorder {
	return m.recorder
}

// SendCreateUserEmail mocks base method.
func (m *MockEmailSender) SendCreateUserEmail(to, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendCreateUserEmail", to, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendCreateUserEmail indicates an expected call of SendCreateUserEmail.
func (mr *MockEmailSenderMockRecorder) SendCreateUserEmail(to, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendCreateUserEmail", reflect.TypeOf((*MockEmailSender)(nil).SendCreateUserEmail), to, token)
}
