// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: chartdb/v1/diagram_service.proto

package chartdb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DiagramService_Get_FullMethodName    = "/chartdb.v1.DiagramService/Get"
	DiagramService_List_FullMethodName   = "/chartdb.v1.DiagramService/List"
	DiagramService_Create_FullMethodName = "/chartdb.v1.DiagramService/Create"
	DiagramService_Update_FullMethodName = "/chartdb.v1.DiagramService/Update"
	DiagramService_Delete_FullMethodName = "/chartdb.v1.DiagramService/Delete"
)

// DiagramServiceClient is the client API for DiagramService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DiagramServiceClient interface {
	Get(ctx context.Context, in *GetDiagramRequest, opts ...grpc.CallOption) (*Diagram, error)
	List(ctx context.Context, in *ListDiagramsRequest, opts ...grpc.CallOption) (*ListDiagramsResponse, error)
	Create(ctx context.Context, in *CreateDiagramRequest, opts ...grpc.CallOption) (*DiagramMetadata, error)
	Update(ctx context.Context, in *UpdateDiagramRequest, opts ...grpc.CallOption) (*DiagramMetadata, error)
	Delete(ctx context.Context, in *DeleteDiagramRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type diagramServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDiagramServiceClient(cc grpc.ClientConnInterface) DiagramServiceClient {
	return &diagramServiceClient{cc}
}

func (c *diagramServiceClient) Get(ctx context.Context, in *GetDiagramRequest, opts ...grpc.CallOption) (*Diagram, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Diagram)
	err := c.cc.Invoke(ctx, DiagramService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diagramServiceClient) List(ctx context.Context, in *ListDiagramsRequest, opts ...grpc.CallOption) (*ListDiagramsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDiagramsResponse)
	err := c.cc.Invoke(ctx, DiagramService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diagramServiceClient) Create(ctx context.Context, in *CreateDiagramRequest, opts ...grpc.CallOption) (*DiagramMetadata, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiagramMetadata)
	err := c.cc.Invoke(ctx, DiagramService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diagramServiceClient) Update(ctx context.Context, in *UpdateDiagramRequest, opts ...grpc.CallOption) (*DiagramMetadata, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiagramMetadata)
	err := c.cc.Invoke(ctx, DiagramService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diagramServiceClient) Delete(ctx context.Context, in *DeleteDiagramRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, DiagramService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiagramServiceServer is the server API for DiagramService service.
// All implementations must embed UnimplementedDiagramServiceServer
// for forward compatibility.
type DiagramServiceServer interface {
	Get(context.Context, *GetDiagramRequest) (*Diagram, error)
	List(context.Context, *ListDiagramsRequest) (*ListDiagramsResponse, error)
	Create(context.Context, *CreateDiagramRequest) (*DiagramMetadata, error)
	Update(context.Context, *UpdateDiagramRequest) (*DiagramMetadata, error)
	Delete(context.Context, *DeleteDiagramRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedDiagramServiceServer()
}

// UnimplementedDiagramServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDiagramServiceServer struct{}

func (UnimplementedDiagramServiceServer) Get(context.Context, *GetDiagramRequest) (*Diagram, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedDiagramServiceServer) List(context.Context, *ListDiagramsRequest) (*ListDiagramsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedDiagramServiceServer) Create(context.Context, *CreateDiagramRequest) (*DiagramMetadata, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedDiagramServiceServer) Update(context.Context, *UpdateDiagramRequest) (*DiagramMetadata, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedDiagramServiceServer) Delete(context.Context, *DeleteDiagramRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedDiagramServiceServer) mustEmbedUnimplementedDiagramServiceServer() {}
func (UnimplementedDiagramServiceServer) testEmbeddedByValue()                        {}

// UnsafeDiagramServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiagramServiceServer will
// result in compilation errors.
type UnsafeDiagramServiceServer interface {
	mustEmbedUnimplementedDiagramServiceServer()
}

func RegisterDiagramServiceServer(s grpc.ServiceRegistrar, srv DiagramServiceServer) {
	// If the following call pancis, it indicates UnimplementedDiagramServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DiagramService_ServiceDesc, srv)
}

func _DiagramService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiagramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagramServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiagramService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagramServiceServer).Get(ctx, req.(*GetDiagramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiagramService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDiagramsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagramServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiagramService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagramServiceServer).List(ctx, req.(*ListDiagramsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiagramService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDiagramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagramServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiagramService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagramServiceServer).Create(ctx, req.(*CreateDiagramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiagramService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDiagramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagramServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiagramService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagramServiceServer).Update(ctx, req.(*UpdateDiagramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiagramService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDiagramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiagramServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiagramService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiagramServiceServer).Delete(ctx, req.(*DeleteDiagramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DiagramService_ServiceDesc is the grpc.ServiceDesc for DiagramService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiagramService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chartdb.v1.DiagramService",
	HandlerType: (*DiagramServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _DiagramService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _DiagramService_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _DiagramService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _DiagramService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _DiagramService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chartdb/v1/diagram_service.proto",
}
