// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: chartdb/v1/diagram.proto

package chartdb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiagramMetadata struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Code            string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	ClientDiagramId string                 `protobuf:"bytes,4,opt,name=client_diagram_id,json=clientDiagramId,proto3" json:"client_diagram_id,omitempty"`
	Name            string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	TablesCount     int64                  `protobuf:"varint,6,opt,name=tables_count,json=tablesCount,proto3" json:"tables_count,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,100,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,101,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DiagramMetadata) Reset() {
	*x = DiagramMetadata{}
	mi := &file_chartdb_v1_diagram_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiagramMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagramMetadata) ProtoMessage() {}

func (x *DiagramMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_chartdb_v1_diagram_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagramMetadata.ProtoReflect.Descriptor instead.
func (*DiagramMetadata) Descriptor() ([]byte, []int) {
	return file_chartdb_v1_diagram_proto_rawDescGZIP(), []int{0}
}

func (x *DiagramMetadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DiagramMetadata) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DiagramMetadata) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DiagramMetadata) GetClientDiagramId() string {
	if x != nil {
		return x.ClientDiagramId
	}
	return ""
}

func (x *DiagramMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DiagramMetadata) GetTablesCount() int64 {
	if x != nil {
		return x.TablesCount
	}
	return 0
}

func (x *DiagramMetadata) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DiagramMetadata) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Diagram struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *DiagramMetadata       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Diagram) Reset() {
	*x = Diagram{}
	mi := &file_chartdb_v1_diagram_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Diagram) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diagram) ProtoMessage() {}

func (x *Diagram) ProtoReflect() protoreflect.Message {
	mi := &file_chartdb_v1_diagram_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diagram.ProtoReflect.Descriptor instead.
func (*Diagram) Descriptor() ([]byte, []int) {
	return file_chartdb_v1_diagram_proto_rawDescGZIP(), []int{1}
}

func (x *Diagram) GetMetadata() *DiagramMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Diagram) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_chartdb_v1_diagram_proto protoreflect.FileDescriptor

const file_chartdb_v1_diagram_proto_rawDesc = "" +
	"\n" +
	"\x18chartdb/v1/diagram.proto\x12\n" +
	"chartdb.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xad\x02\n" +
	"\x0fDiagramMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12*\n" +
	"\x11client_diagram_id\x18\x04 \x01(\tR\x0fclientDiagramId\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12!\n" +
	"\ftables_count\x18\x06 \x01(\x03R\vtablesCount\x129\n" +
	"\n" +
	"created_at\x18d \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtJ\x04\b\a\x10d\"\\\n" +
	"\aDiagram\x127\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1b.chartdb.v1.DiagramMetadataR\bmetadata\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontentB\x14Z\x12chartdb/v1;chartdbb\x06proto3"

var (
	file_chartdb_v1_diagram_proto_rawDescOnce sync.Once
	file_chartdb_v1_diagram_proto_rawDescData []byte
)

func file_chartdb_v1_diagram_proto_rawDescGZIP() []byte {
	file_chartdb_v1_diagram_proto_rawDescOnce.Do(func() {
		file_chartdb_v1_diagram_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chartdb_v1_diagram_proto_rawDesc), len(file_chartdb_v1_diagram_proto_rawDesc)))
	})
	return file_chartdb_v1_diagram_proto_rawDescData
}

var file_chartdb_v1_diagram_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_chartdb_v1_diagram_proto_goTypes = []any{
	(*DiagramMetadata)(nil),       // 0: chartdb.v1.DiagramMetadata
	(*Diagram)(nil),               // 1: chartdb.v1.Diagram
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_chartdb_v1_diagram_proto_depIdxs = []int32{
	2, // 0: chartdb.v1.DiagramMetadata.created_at:type_name -> google.protobuf.Timestamp
	2, // 1: chartdb.v1.DiagramMetadata.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: chartdb.v1.Diagram.metadata:type_name -> chartdb.v1.DiagramMetadata
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_chartdb_v1_diagram_proto_init() }
func file_chartdb_v1_diagram_proto_init() {
	if File_chartdb_v1_diagram_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chartdb_v1_diagram_proto_rawDesc), len(file_chartdb_v1_diagram_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chartdb_v1_diagram_proto_goTypes,
		DependencyIndexes: file_chartdb_v1_diagram_proto_depIdxs,
		MessageInfos:      file_chartdb_v1_diagram_proto_msgTypes,
	}.Build()
	File_chartdb_v1_diagram_proto = out.File
	file_chartdb_v1_diagram_proto_goTypes = nil
	file_chartdb_v1_diagram_proto_depIdxs = nil
}
