// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: chartdb/v1/diagram_service.proto

package chartdb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDiagramRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Could be diagram ID or its code
	Identifier    string `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiagramRequest) Reset() {
	*x = GetDiagramRequest{}
	mi := &file_chartdb_v1_diagram_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiagramRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiagramRequest) ProtoMessage() {}

func (x *GetDiagramRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chartdb_v1_diagram_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiagramRequest.ProtoReflect.Descriptor instead.
func (*GetDiagramRequest) Descriptor() ([]byte, []int) {
	return file_chartdb_v1_diagram_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetDiagramRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

type ListDiagramsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        string                 `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDiagramsRequest) Reset() {
	*x = ListDiagramsRequest{}
	mi := &file_chartdb_v1_diagram_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDiagramsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDiagramsRequest) ProtoMessage() {}

func (x *ListDiagramsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chartdb_v1_diagram_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDiagramsRequest.ProtoReflect.Descriptor instead.
func (*ListDiagramsRequest) Descriptor() ([]byte, []int) {
	return file_chartdb_v1_diagram_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListDiagramsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type ListDiagramsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Diagrams      []*DiagramMetadata     `protobuf:"bytes,1,rep,name=diagrams,proto3" json:"diagrams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDiagramsResponse) Reset() {
	*x = ListDiagramsResponse{}
	mi := &file_chartdb_v1_diagram_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDiagramsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDiagramsResponse) ProtoMessage() {}

func (x *ListDiagramsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chartdb_v1_diagram_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDiagramsResponse.ProtoReflect.Descriptor instead.
func (*ListDiagramsResponse) Descriptor() ([]byte, []int) {
	return file_chartdb_v1_diagram_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListDiagramsResponse) GetDiagrams() []*DiagramMetadata {
	if x != nil {
		return x.Diagrams
	}
	return nil
}

type CreateDiagramRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ClientDiagramId string                 `protobuf:"bytes,2,opt,name=client_diagram_id,json=clientDiagramId,proto3" json:"client_diagram_id,omitempty"`
	Content         string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Name            string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	TablesCount     int64                  `protobuf:"varint,5,opt,name=tables_count,json=tablesCount,proto3" json:"tables_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateDiagramRequest) Reset() {
	*x = CreateDiagramRequest{}
	mi := &file_chartdb_v1_diagram_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDiagramRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDiagramRequest) ProtoMessage() {}

func (x *CreateDiagramRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chartdb_v1_diagram_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDiagramRequest.ProtoReflect.Descriptor instead.
func (*CreateDiagramRequest) Descriptor() ([]byte, []int) {
	return file_chartdb_v1_diagram_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateDiagramRequest) GetClientDiagramId() string {
	if x != nil {
		return x.ClientDiagramId
	}
	return ""
}

func (x *CreateDiagramRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateDiagramRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDiagramRequest) GetTablesCount() int64 {
	if x != nil {
		return x.TablesCount
	}
	return 0
}

type UpdateDiagramRequest struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Id            string                             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Fields        *UpdateDiagramRequest_UpdateFields `protobuf:"bytes,2,opt,name=fields,proto3" json:"fields,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask             `protobuf:"bytes,3,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDiagramRequest) Reset() {
	*x = UpdateDiagramRequest{}
	mi := &file_chartdb_v1_diagram_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDiagramRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDiagramRequest) ProtoMessage() {}

func (x *UpdateDiagramRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chartdb_v1_diagram_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDiagramRequest.ProtoReflect.Descriptor instead.
func (*UpdateDiagramRequest) Descriptor() ([]byte, []int) {
	return file_chartdb_v1_diagram_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateDiagramRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDiagramRequest) GetFields() *UpdateDiagramRequest_UpdateFields {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *UpdateDiagramRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type DeleteDiagramRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDiagramRequest) Reset() {
	*x = DeleteDiagramRequest{}
	mi := &file_chartdb_v1_diagram_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDiagramRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDiagramRequest) ProtoMessage() {}

func (x *DeleteDiagramRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chartdb_v1_diagram_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDiagramRequest.ProtoReflect.Descriptor instead.
func (*DeleteDiagramRequest) Descriptor() ([]byte, []int) {
	return file_chartdb_v1_diagram_service_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteDiagramRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateDiagramRequest_UpdateFields struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TablesCount   int64                  `protobuf:"varint,3,opt,name=tables_count,json=tablesCount,proto3" json:"tables_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDiagramRequest_UpdateFields) Reset() {
	*x = UpdateDiagramRequest_UpdateFields{}
	mi := &file_chartdb_v1_diagram_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDiagramRequest_UpdateFields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDiagramRequest_UpdateFields) ProtoMessage() {}

func (x *UpdateDiagramRequest_UpdateFields) ProtoReflect() protoreflect.Message {
	mi := &file_chartdb_v1_diagram_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDiagramRequest_UpdateFields.ProtoReflect.Descriptor instead.
func (*UpdateDiagramRequest_UpdateFields) Descriptor() ([]byte, []int) {
	return file_chartdb_v1_diagram_service_proto_rawDescGZIP(), []int{4, 0}
}

func (x *UpdateDiagramRequest_UpdateFields) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateDiagramRequest_UpdateFields) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateDiagramRequest_UpdateFields) GetTablesCount() int64 {
	if x != nil {
		return x.TablesCount
	}
	return 0
}

var File_chartdb_v1_diagram_service_proto protoreflect.FileDescriptor

const file_chartdb_v1_diagram_service_proto_rawDesc = "" +
	"\n" +
	" chartdb/v1/diagram_service.proto\x12\n" +
	"chartdb.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x18chartdb/v1/diagram.proto\";\n" +
	"\x11GetDiagramRequest\x12&\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"identifier\"-\n" +
	"\x13ListDiagramsRequest\x12\x16\n" +
	"\x06filter\x18\x01 \x01(\tR\x06filter\"O\n" +
	"\x14ListDiagramsResponse\x127\n" +
	"\bdiagrams\x18\x01 \x03(\v2\x1b.chartdb.v1.DiagramMetadataR\bdiagrams\"\xb7\x01\n" +
	"\x14CreateDiagramRequest\x126\n" +
	"\x11client_diagram_id\x18\x02 \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x04R\x0fclientDiagramId\x12 \n" +
	"\acontent\x18\x03 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\acontent\x12\x1a\n" +
	"\x04name\x18\x04 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\x12)\n" +
	"\ftables_count\x18\x05 \x01(\x03B\x06\xbaH\x03\xc8\x01\x01R\vtablesCount\"\x93\x02\n" +
	"\x14UpdateDiagramRequest\x12\x16\n" +
	"\x02id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x02id\x12E\n" +
	"\x06fields\x18\x02 \x01(\v2-.chartdb.v1.UpdateDiagramRequest.UpdateFieldsR\x06fields\x12;\n" +
	"\vupdate_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\x1a_\n" +
	"\fUpdateFields\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\ftables_count\x18\x03 \x01(\x03R\vtablesCount\".\n" +
	"\x14DeleteDiagramRequest\x12\x16\n" +
	"\x02id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x02id2\xa4\x04\n" +
	"\x0eDiagramService\x12d\n" +
	"\x03Get\x12\x1d.chartdb.v1.GetDiagramRequest\x1a\x13.chartdb.v1.Diagram\")\x82\xd3\xe4\x93\x02#\x12!/chartdb/v1/diagrams/{identifier}\x12g\n" +
	"\x04List\x12\x1f.chartdb.v1.ListDiagramsRequest\x1a .chartdb.v1.ListDiagramsResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/chartdb/v1/diagrams\x12h\n" +
	"\x06Create\x12 .chartdb.v1.CreateDiagramRequest\x1a\x1b.chartdb.v1.DiagramMetadata\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/chartdb/v1/diagrams\x12r\n" +
	"\x06Update\x12 .chartdb.v1.UpdateDiagramRequest\x1a\x1b.chartdb.v1.DiagramMetadata\")\x82\xd3\xe4\x93\x02#:\x06fields2\x19/chartdb/v1/diagrams/{id}\x12e\n" +
	"\x06Delete\x12 .chartdb.v1.DeleteDiagramRequest\x1a\x16.google.protobuf.Empty\"!\x82\xd3\xe4\x93\x02\x1b*\x19/chartdb/v1/diagrams/{id}B\x14Z\x12chartdb/v1;chartdbb\x06proto3"

var (
	file_chartdb_v1_diagram_service_proto_rawDescOnce sync.Once
	file_chartdb_v1_diagram_service_proto_rawDescData []byte
)

func file_chartdb_v1_diagram_service_proto_rawDescGZIP() []byte {
	file_chartdb_v1_diagram_service_proto_rawDescOnce.Do(func() {
		file_chartdb_v1_diagram_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chartdb_v1_diagram_service_proto_rawDesc), len(file_chartdb_v1_diagram_service_proto_rawDesc)))
	})
	return file_chartdb_v1_diagram_service_proto_rawDescData
}

var file_chartdb_v1_diagram_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_chartdb_v1_diagram_service_proto_goTypes = []any{
	(*GetDiagramRequest)(nil),                 // 0: chartdb.v1.GetDiagramRequest
	(*ListDiagramsRequest)(nil),               // 1: chartdb.v1.ListDiagramsRequest
	(*ListDiagramsResponse)(nil),              // 2: chartdb.v1.ListDiagramsResponse
	(*CreateDiagramRequest)(nil),              // 3: chartdb.v1.CreateDiagramRequest
	(*UpdateDiagramRequest)(nil),              // 4: chartdb.v1.UpdateDiagramRequest
	(*DeleteDiagramRequest)(nil),              // 5: chartdb.v1.DeleteDiagramRequest
	(*UpdateDiagramRequest_UpdateFields)(nil), // 6: chartdb.v1.UpdateDiagramRequest.UpdateFields
	(*DiagramMetadata)(nil),                   // 7: chartdb.v1.DiagramMetadata
	(*fieldmaskpb.FieldMask)(nil),             // 8: google.protobuf.FieldMask
	(*Diagram)(nil),                           // 9: chartdb.v1.Diagram
	(*emptypb.Empty)(nil),                     // 10: google.protobuf.Empty
}
var file_chartdb_v1_diagram_service_proto_depIdxs = []int32{
	7,  // 0: chartdb.v1.ListDiagramsResponse.diagrams:type_name -> chartdb.v1.DiagramMetadata
	6,  // 1: chartdb.v1.UpdateDiagramRequest.fields:type_name -> chartdb.v1.UpdateDiagramRequest.UpdateFields
	8,  // 2: chartdb.v1.UpdateDiagramRequest.update_mask:type_name -> google.protobuf.FieldMask
	0,  // 3: chartdb.v1.DiagramService.Get:input_type -> chartdb.v1.GetDiagramRequest
	1,  // 4: chartdb.v1.DiagramService.List:input_type -> chartdb.v1.ListDiagramsRequest
	3,  // 5: chartdb.v1.DiagramService.Create:input_type -> chartdb.v1.CreateDiagramRequest
	4,  // 6: chartdb.v1.DiagramService.Update:input_type -> chartdb.v1.UpdateDiagramRequest
	5,  // 7: chartdb.v1.DiagramService.Delete:input_type -> chartdb.v1.DeleteDiagramRequest
	9,  // 8: chartdb.v1.DiagramService.Get:output_type -> chartdb.v1.Diagram
	2,  // 9: chartdb.v1.DiagramService.List:output_type -> chartdb.v1.ListDiagramsResponse
	7,  // 10: chartdb.v1.DiagramService.Create:output_type -> chartdb.v1.DiagramMetadata
	7,  // 11: chartdb.v1.DiagramService.Update:output_type -> chartdb.v1.DiagramMetadata
	10, // 12: chartdb.v1.DiagramService.Delete:output_type -> google.protobuf.Empty
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_chartdb_v1_diagram_service_proto_init() }
func file_chartdb_v1_diagram_service_proto_init() {
	if File_chartdb_v1_diagram_service_proto != nil {
		return
	}
	file_chartdb_v1_diagram_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chartdb_v1_diagram_service_proto_rawDesc), len(file_chartdb_v1_diagram_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chartdb_v1_diagram_service_proto_goTypes,
		DependencyIndexes: file_chartdb_v1_diagram_service_proto_depIdxs,
		MessageInfos:      file_chartdb_v1_diagram_service_proto_msgTypes,
	}.Build()
	File_chartdb_v1_diagram_service_proto = out.File
	file_chartdb_v1_diagram_service_proto_goTypes = nil
	file_chartdb_v1_diagram_service_proto_depIdxs = nil
}
