// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: chartdb/v1/user_service.proto

package chartdb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_chartdb_v1_user_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chartdb_v1_user_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_chartdb_v1_user_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_chartdb_v1_user_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chartdb_v1_user_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_chartdb_v1_user_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserRequest) Reset() {
	*x = LoginUserRequest{}
	mi := &file_chartdb_v1_user_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserRequest) ProtoMessage() {}

func (x *LoginUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chartdb_v1_user_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserRequest.ProtoReflect.Descriptor instead.
func (*LoginUserRequest) Descriptor() ([]byte, []int) {
	return file_chartdb_v1_user_service_proto_rawDescGZIP(), []int{2}
}

func (x *LoginUserRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *LoginUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginUserResponse) Reset() {
	*x = LoginUserResponse{}
	mi := &file_chartdb_v1_user_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUserResponse) ProtoMessage() {}

func (x *LoginUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chartdb_v1_user_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUserResponse.ProtoReflect.Descriptor instead.
func (*LoginUserResponse) Descriptor() ([]byte, []int) {
	return file_chartdb_v1_user_service_proto_rawDescGZIP(), []int{3}
}

func (x *LoginUserResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginUserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ConfirmUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           string                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmUserRequest) Reset() {
	*x = ConfirmUserRequest{}
	mi := &file_chartdb_v1_user_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmUserRequest) ProtoMessage() {}

func (x *ConfirmUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chartdb_v1_user_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmUserRequest.ProtoReflect.Descriptor instead.
func (*ConfirmUserRequest) Descriptor() ([]byte, []int) {
	return file_chartdb_v1_user_service_proto_rawDescGZIP(), []int{4}
}

func (x *ConfirmUserRequest) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

var File_chartdb_v1_user_service_proto protoreflect.FileDescriptor

const file_chartdb_v1_user_service_proto_rawDesc = "" +
	"\n" +
	"\x1dchartdb/v1/user_service.proto\x12\n" +
	"chartdb.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x15chartdb/v1/user.proto\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"M\n" +
	"\x11CreateUserRequest\x12\x1c\n" +
	"\x05login\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"T\n" +
	"\x10LoginUserRequest\x12\x1c\n" +
	"\x05login\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x05login\x12\"\n" +
	"\bpassword\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\bpassword\"B\n" +
	"\x11LoginUserResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\".\n" +
	"\x12ConfirmUserRequest\x12\x18\n" +
	"\x03cid\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x03cid2\x88\x03\n" +
	"\vUserService\x12S\n" +
	"\x03Get\x12\x1a.chartdb.v1.GetUserRequest\x1a\x10.chartdb.v1.User\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/chartdb/v1/users/{id}\x12W\n" +
	"\x06Create\x12\x1d.chartdb.v1.CreateUserRequest\x1a\x10.chartdb.v1.User\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/chartdb/v1/users\x12h\n" +
	"\x05Login\x12\x1c.chartdb.v1.LoginUserRequest\x1a\x1d.chartdb.v1.LoginUserResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/chartdb/v1/users:login\x12a\n" +
	"\aConfirm\x12\x1e.chartdb.v1.ConfirmUserRequest\x1a\x10.chartdb.v1.User\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/chartdb/v1/users:confirmB\x14Z\x12chartdb/v1;chartdbb\x06proto3"

var (
	file_chartdb_v1_user_service_proto_rawDescOnce sync.Once
	file_chartdb_v1_user_service_proto_rawDescData []byte
)

func file_chartdb_v1_user_service_proto_rawDescGZIP() []byte {
	file_chartdb_v1_user_service_proto_rawDescOnce.Do(func() {
		file_chartdb_v1_user_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chartdb_v1_user_service_proto_rawDesc), len(file_chartdb_v1_user_service_proto_rawDesc)))
	})
	return file_chartdb_v1_user_service_proto_rawDescData
}

var file_chartdb_v1_user_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_chartdb_v1_user_service_proto_goTypes = []any{
	(*GetUserRequest)(nil),     // 0: chartdb.v1.GetUserRequest
	(*CreateUserRequest)(nil),  // 1: chartdb.v1.CreateUserRequest
	(*LoginUserRequest)(nil),   // 2: chartdb.v1.LoginUserRequest
	(*LoginUserResponse)(nil),  // 3: chartdb.v1.LoginUserResponse
	(*ConfirmUserRequest)(nil), // 4: chartdb.v1.ConfirmUserRequest
	(*User)(nil),               // 5: chartdb.v1.User
}
var file_chartdb_v1_user_service_proto_depIdxs = []int32{
	0, // 0: chartdb.v1.UserService.Get:input_type -> chartdb.v1.GetUserRequest
	1, // 1: chartdb.v1.UserService.Create:input_type -> chartdb.v1.CreateUserRequest
	2, // 2: chartdb.v1.UserService.Login:input_type -> chartdb.v1.LoginUserRequest
	4, // 3: chartdb.v1.UserService.Confirm:input_type -> chartdb.v1.ConfirmUserRequest
	5, // 4: chartdb.v1.UserService.Get:output_type -> chartdb.v1.User
	5, // 5: chartdb.v1.UserService.Create:output_type -> chartdb.v1.User
	3, // 6: chartdb.v1.UserService.Login:output_type -> chartdb.v1.LoginUserResponse
	5, // 7: chartdb.v1.UserService.Confirm:output_type -> chartdb.v1.User
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chartdb_v1_user_service_proto_init() }
func file_chartdb_v1_user_service_proto_init() {
	if File_chartdb_v1_user_service_proto != nil {
		return
	}
	file_chartdb_v1_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chartdb_v1_user_service_proto_rawDesc), len(file_chartdb_v1_user_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chartdb_v1_user_service_proto_goTypes,
		DependencyIndexes: file_chartdb_v1_user_service_proto_depIdxs,
		MessageInfos:      file_chartdb_v1_user_service_proto_msgTypes,
	}.Build()
	File_chartdb_v1_user_service_proto = out.File
	file_chartdb_v1_user_service_proto_goTypes = nil
	file_chartdb_v1_user_service_proto_depIdxs = nil
}
