// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: chartdb/v1/user.proto

package chartdb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserType int32

const (
	UserType_USER_TYPE_UNSPECIFIED UserType = 0
	UserType_USER_TYPE_GUEST       UserType = 1
	UserType_USER_TYPE_STUDENT     UserType = 2
	UserType_USER_TYPE_TEACHER     UserType = 3
	UserType_USER_TYPE_ADMIN       UserType = 4
)

// Enum value maps for UserType.
var (
	UserType_name = map[int32]string{
		0: "USER_TYPE_UNSPECIFIED",
		1: "USER_TYPE_GUEST",
		2: "USER_TYPE_STUDENT",
		3: "USER_TYPE_TEACHER",
		4: "USER_TYPE_ADMIN",
	}
	UserType_value = map[string]int32{
		"USER_TYPE_UNSPECIFIED": 0,
		"USER_TYPE_GUEST":       1,
		"USER_TYPE_STUDENT":     2,
		"USER_TYPE_TEACHER":     3,
		"USER_TYPE_ADMIN":       4,
	}
)

func (x UserType) Enum() *UserType {
	p := new(UserType)
	*p = x
	return p
}

func (x UserType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserType) Descriptor() protoreflect.EnumDescriptor {
	return file_chartdb_v1_user_proto_enumTypes[0].Descriptor()
}

func (UserType) Type() protoreflect.EnumType {
	return &file_chartdb_v1_user_proto_enumTypes[0]
}

func (x UserType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserType.Descriptor instead.
func (UserType) EnumDescriptor() ([]byte, []int) {
	return file_chartdb_v1_user_proto_rawDescGZIP(), []int{0}
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Login         string                 `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Type          UserType               `protobuf:"varint,3,opt,name=type,proto3,enum=chartdb.v1.UserType" json:"type,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,100,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,101,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_chartdb_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_chartdb_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_chartdb_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *User) GetType() UserType {
	if x != nil {
		return x.Type
	}
	return UserType_USER_TYPE_UNSPECIFIED
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_chartdb_v1_user_proto protoreflect.FileDescriptor

const file_chartdb_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x15chartdb/v1/user.proto\x12\n" +
	"chartdb.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd2\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\x12(\n" +
	"\x04type\x18\x03 \x01(\x0e2\x14.chartdb.v1.UserTypeR\x04type\x129\n" +
	"\n" +
	"created_at\x18d \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtJ\x04\b\x04\x10d*}\n" +
	"\bUserType\x12\x19\n" +
	"\x15USER_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fUSER_TYPE_GUEST\x10\x01\x12\x15\n" +
	"\x11USER_TYPE_STUDENT\x10\x02\x12\x15\n" +
	"\x11USER_TYPE_TEACHER\x10\x03\x12\x13\n" +
	"\x0fUSER_TYPE_ADMIN\x10\x04B\x14Z\x12chartdb/v1;chartdbb\x06proto3"

var (
	file_chartdb_v1_user_proto_rawDescOnce sync.Once
	file_chartdb_v1_user_proto_rawDescData []byte
)

func file_chartdb_v1_user_proto_rawDescGZIP() []byte {
	file_chartdb_v1_user_proto_rawDescOnce.Do(func() {
		file_chartdb_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chartdb_v1_user_proto_rawDesc), len(file_chartdb_v1_user_proto_rawDesc)))
	})
	return file_chartdb_v1_user_proto_rawDescData
}

var file_chartdb_v1_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chartdb_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_chartdb_v1_user_proto_goTypes = []any{
	(UserType)(0),                 // 0: chartdb.v1.UserType
	(*User)(nil),                  // 1: chartdb.v1.User
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_chartdb_v1_user_proto_depIdxs = []int32{
	0, // 0: chartdb.v1.User.type:type_name -> chartdb.v1.UserType
	2, // 1: chartdb.v1.User.created_at:type_name -> google.protobuf.Timestamp
	2, // 2: chartdb.v1.User.updated_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_chartdb_v1_user_proto_init() }
func file_chartdb_v1_user_proto_init() {
	if File_chartdb_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chartdb_v1_user_proto_rawDesc), len(file_chartdb_v1_user_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chartdb_v1_user_proto_goTypes,
		DependencyIndexes: file_chartdb_v1_user_proto_depIdxs,
		EnumInfos:         file_chartdb_v1_user_proto_enumTypes,
		MessageInfos:      file_chartdb_v1_user_proto_msgTypes,
	}.Build()
	File_chartdb_v1_user_proto = out.File
	file_chartdb_v1_user_proto_goTypes = nil
	file_chartdb_v1_user_proto_depIdxs = nil
}
